[redirects]
  from = "/*/*/"
  to = "/index.html"
  status = 200

[build]
command = "npm run build"
publish = "dist"

[build.processing]
skip_processing = false

[build.environment]
NODE_VERSION = "18"
NETLIFY_USE_YARN_CACHE = "true"

[build.lifecycle]
ignore = "git diff --quiet HEAD^ HEAD ./src || exit 1"
